### ISSUE TITLE
Replace dirac-wms-job-get-output by the appropriate DIRAC call

### ISSUE THREAD

**Issue by apuignav** [ibab/grid-submission#3]
This is easy: [http://diracgrid.org/files/docs/CodeDocumentation/Interfaces/API/Dirac.html#DIRAC.Interfaces.API.Dirac.Dirac.getJobOutputData](http://diracgrid.org/files/docs/CodeDocumentation/Interfaces/API/Dirac.html#DIRAC.Interfaces.API.Dirac.Dirac.getJobOutputData).

The only question is: is asynchronicity preserved?

PS: I'll try to submit a PR for this, but leaving the issue allows me to remember to do it.

**Comment by ibab** [comment]
The reason I called the external script is that `getJobOutputData` doesn't seem to be thread safe, unfortunately.
It started placing the output directories randomly into the subdirectories of other output directories. :(
Maybe the current working directory is changed somewhere in the dirac API.

**Comment by apuignav** [comment]
Could this be fixed with the usage of the `destinationDir` argument?

**Comment by ibab** [comment]
It didn't seem to make a difference :(

**Comment by apuignav** [comment]
Can you confirm you used `abspath`? I'm digging deep in DIRAC's code and I don't see why this would fail otherwise...

**Comment by ibab** [comment]
Ah, that could have been it!
I thought that it would do an `abspath` itself if necessary.

**Comment by apuignav** [comment]
I see a nice `os.path.realpath`, which would actually screw up if for some reason the dir had changed, wouldn't it?
